# Generated by Django 5.0.3 on 2024-04-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='cost',
            new_name='rental_price',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='house',
            name='hall',
        ),
    ]
