# Generated by Django 5.0.3 on 2024-04-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_desc_house_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='area',
        ),
        migrations.RemoveField(
            model_name='house',
            name='floor',
        ),
    ]
