# Generated by Django 5.0.3 on 2024-04-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_state_user_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
