# Generated by Django 5.0.3 on 2024-04-11 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_contact_subject_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='bedrooms',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='rental_price',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='description',
            new_name='desc',
        ),
    ]
