# Generated by Django 5.0.3 on 2024-04-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_bedrooms_house_bedroom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
