# Generated by Django 5.0.3 on 2024-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_house_img_houseimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houseimage',
            old_name='image',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
