# Generated by Django 5.0.3 on 2024-04-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_houseimage_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
