# Generated by Django 5.0.3 on 2024-04-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='payment_method',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='payment_option',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
